version: 2
updates:
  # Maintain dependencies for cargo
  - package-ecosystem: "cargo"
    directory: "/googleplay-protobuf/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    assignees:
      - "hainish"
    commit-message:
      prefix: "cargo-update-googleplay-protobuf"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "hainish"
    versioning-strategy: auto
  - package-ecosystem: "cargo"
    directory: "/gpapi/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    assignees:
      - "hainish"
    commit-message:
      prefix: "cargo-update-gpapi"
    labels:
      - "dependencies"
    pull-request-branch-name:
      separator: "-"
    reviewers:
      - "hainish"
    versioning-strategy: auto
