[package]
name = "gpapi"
version = "0.1.0"
authors = ["David Weinstein <dweinst@insitusec.com>", "Bill Budington <bill@eff.org>"]
build = "build.rs"
license = "MIT"
edition = "2018"

[dependencies]
protobuf = { version = "2", features = ["with-bytes", "with-serde"] }
reqwest = "0.11"
bytes = "1"
openssl = "0.10"
base64 = "0.13"
byteorder = "1"
hex = "0.4"
lazy_static = "1.4"
hyper = { version = "0.14", features = ["full"] }
hyper-openssl = "0.9"
tokio = { version = "1", features = ["full"] }
googleplay-protobuf = { path = "../googleplay-protobuf", features = ["with-serde"] }
bincode = "1"

[build-dependencies]
googleplay-protobuf = { path = "../googleplay-protobuf", features = ["with-serde"] }
protobuf = { version = "2", features = ["with-bytes", "with-serde"] }
bincode = "1"
configparser = "2"
